server:
  port: 8084

spring:
  application:
    name: campus-assistance-backend
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${cab.db.username}
    password: ${cab.db.password}
    url: jdbc:mysql://${cab.db.host}:${cab.db.port}/${cab.db.database}?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&nullCatalogMeansCurrent=true

  #swagger3.0
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

flowable:
  #自动更新表结构
  database-schema-update: false
  #定时任务
  async-executor-activate: false
  #自动部署
  check-process-definitions: false

qiniu:
  accessKey: ${QINIU_ACCESS_KEY}
  secretKey: ${QINIU_SECRET_KEY}
  bucketName: siyu-bucket
  url: http://img.siyu.site

jwt:
  refresh: 24
  expire: 256
  secret: ${PROJECT_JWT_SECRET}

user:
  salt: ${PROJECT_USER_SALT}